### PR TITLE
Add build dependencies for sqlite3

### PR DESCRIPTION
**Pull request by y0ast**
# Proposed Changes

Add build dependencies for [node-gyp](https://github.com/nodejs/node-gyp#installation), such that sqlite3@5.0.0 can be built, which is an optional dependency of The Lounge that enables loading history.

I've tested this locally and it allows restoring messages as expected.

I used python2, because node-gyp searches for `python` executable, and the python3 package only provides `python3`. Since it's a build dependency I thought it should be fine.

## Related Issues

Fixes: https://github.com/hassio-addons/addon-thelounge/issues/11

### CODE REVIEW

**Comment by y0ast** [comment]
@frenck Given that you recently made some changes to this repo, would you be open to merge this PR?

I've been running this version of thelounge since I put up the PR without issues.

**Comment by frenck** [comment]
@y0ast Yes.

I'm currently replacing the CI across all add-ons. After that is done, I start a maintenance cycle.

**Comment by y0ast** [comment]
Awesome, thanks man :)

**Review by frenck — APPROVED** [review]
Thanks, @y0ast 👍

**Pull request merged**
